env: crossroads

env_args:
  episode_limit: 100
  debug: True
  agent_velocity: 5
  channel_size: 1
  reward_success: 1
  reward_failure: -1

t_max: 1000000
test_nepisode: 5
test_interval: 5000
log_interval: 5000
runner_log_interval: 5000
learner_log_interval: 5000

buffer_size: 5000 # Size of the replay buffer
lr: 0.0005 # Learning rate for agents
gamma: 0.98