env: diamond

env_args:
  episode_limit: 300
  debug: True
  agent_velocity: 3
  guard_velocity: 3
  channel_size: 1
  lidar_angle: 360
  lidar_interval: 90
  reward_success: 100
  reward_failure: -100

t_max: 100000
test_nepisode: 5
test_interval: 5000
log_interval: 5000
runner_log_interval: 5000
learner_log_interval: 5000