env: guess

t_max: 1000
test_nepisode: 10
test_interval: 50
log_interval: 5000
runner_log_interval: 50
learner_log_interval: 5000

buffer_size: 1000 # Size of the replay buffer
lr: 0.0005 # Learning rate for agents
gamma: 0.99

episode_limit: 20